# bluetoother
dist: xenial
sudo: true
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
#      - g++-5
      - libgtkmm-3.0-dev
      - libbluetooth-dev

script:
  - apt-get -y install libgtkmm-3.0-dev libbluetooth-dev  g++-5
  - mkdir build
  - cd build
#  - CXX=/usr/bin/g++-5  CC=/usr/bin/gcc-5  cmake  -D CMAKE_BUILD_TYPE=Release  ..
  - cmake  -D CMAKE_BUILD_TYPE=Release  ..
  - make  -j2

